"""Initial db migration

Revision ID: 109fc620a391
Revises: 
Create Date: 2025-05-17 19:27:08.918599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '109fc620a391'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_index('email', table_name='users')
    op.drop_index('username', table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
