"""Nowa migracja od zera

Revision ID: 2e4b6c55ff4d
Revises: 
Create Date: 2025-05-21 23:04:16.287876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e4b6c55ff4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('trip_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_table('trip_locations',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.alter_column('locations', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index('ix_locations_id', table_name='locations')
    op.create_index(op.f('ix_locations_location_id'), 'locations', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_location_id'), table_name='locations')
    op.create_index('ix_locations_id', 'locations', ['location_id'], unique=False)
    op.alter_column('locations', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_table('trip_locations')
    op.drop_table('trips')
    # ### end Alembic commands ###
