"""Add points and total_distance to User

Revision ID: cc0c67d03d82
Revises: d927051f74e6
Create Date: 2025-05-28 00:05:03.769496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0c67d03d82'
down_revision: Union[str, None] = 'd927051f74e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_distance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_distance')
    op.drop_column('users', 'points')
    # ### end Alembic commands ###
